export const actions = Object.freeze({
  SET_POINT: 'SET_POINT',
  UNSET_POINT: 'UNSET_POINT',
  RESET_SPEC: 'RESET_SPEC',
  RESET_ALL: 'RESET_ALL',
  SET_GLYPH: 'SET_GLYPH',
  SELECT_HERO: 'SELECT_HERO',
});